[project]
name = "tiny-dsa-extraction-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "excel-grapher",
]

[tool.uv.sources]
excel-grapher = { git = "https://github.com/Teal-Insights/excel-grapher.git" }

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
    "ruff>=0.15.12",
    "ty>=0.0.34",
]
