from pathlib import Path
from typing import Literal, Annotated

from excel_grapher.core.cell_types import RealBetween, Between
from excel_grapher.grapher import (
    DependencyGraph,
    DynamicRefConfig,
    create_dependency_graph,
)


# Load the Tiny DSA workbook
workbook_path = Path("data/tiny-dsa.xlsx")

targets = ["output_baseline", "output_shocked", "output_delta"]

"""
To support programmatic testing, we constrain all leaf cells, not just
those required for dynamic ref resolution.

Note: constraints are not currently stored in the graph object, so test
harness must load them directly from the constraints dictionary.

Constraints generated by Composer 2 Fast with the prompt, "Investigate
these cells in data/tiny-dsa.xlsx. Which are meant to be constants,
and which user inputs? What are the expected input domains (e.g.,
permissible inputs that might be entered into user-configurable input
cells)?"
"""

# Required constraints
required_constraints = {
    "Inputs!A10": Literal["Borvelia"],
    "Inputs!A11": Literal["Litellia"],
    "Inputs!A12": Literal["Aurelium"],
    "Inputs!B22": Literal[1, 2, 3],
    "Inputs!B5": Literal["Borvelia", "Litellia", "Aurelium"],
}

# Additional constraints not required for dynamic ref resolution
# (included to support testing of the extraction pipeline)
_cols = ("C", "D", "E", "F", "G")
constraints = required_constraints | {
    "Engine!C5": Literal[1],
    "Engine!D5": Literal[2],
    "Engine!E5": Literal[3],
    "Engine!F5": Literal[4],
    "Engine!G5": Literal[5],
    "Inputs!B10": Annotated[float, RealBetween(0.0, 200.0)],
    "Inputs!B11": Annotated[float, RealBetween(0.0, 200.0)],
    "Inputs!B12": Annotated[float, RealBetween(0.0, 200.0)],
    "Inputs!B21": Annotated[int, Between(1, 5)],
    "Inputs!B26": Annotated[float, RealBetween(-30.0, 30.0)],
    "Inputs!C26": Annotated[float, RealBetween(-30.0, 30.0)],
    "Inputs!D26": Annotated[float, RealBetween(-30.0, 30.0)],
    **{f"Inputs!{c}16": Annotated[float, RealBetween(-10.0, 15.0)] for c in _cols},
    **{f"Inputs!{c}17": Annotated[float, RealBetween(0.0, 20.0)] for c in _cols},
    **{f"Inputs!{c}18": Annotated[float, RealBetween(-15.0, 15.0)] for c in _cols},
}

config = DynamicRefConfig.from_constraints(required_constraints, {})
graph: DependencyGraph = create_dependency_graph(
    workbook_path,
    targets,
    load_values=True,
    dynamic_refs=config,
)
