from pathlib import Path
from typing import Annotated, Iterable, Literal, Mapping, get_args, get_origin

from excel_grapher.core.cell_types import RealBetween, Between
from excel_grapher.exporter import CodeGenerator
from excel_grapher.grapher import (
    DependencyGraph,
    DynamicRefConfig,
    create_dependency_graph,
)
from excel_grapher.series_bindings import (
    derive_input_series,
    derive_output_series,
    load_series_bindings,
    validate_series_bindings,
)

from src.docstring_callback import available_docstring_callback

# Load the Tiny DSA workbook
repo_root = Path(__file__).resolve().parents[1]
workbook_path = repo_root / "data/tiny-dsa.xlsx"
bindings_path = repo_root / "bindings"

targets = ["output_baseline", "output_shocked", "output_delta"]
series_bindings = load_series_bindings(bindings_path)

# ------------------------------------------------------------
# Constraint configuration
# ------------------------------------------------------------

"""
To support programmatic testing, we constrain all leaf cells, not just
those required for dynamic ref resolution.

Note: constraints are not (yet) stored on the graph object; tests load
them from the constraints dictionary. Leaf classification is stored on
the graph as `graph.leaf_classification` after extraction.

Constraints generated by Composer 2 Fast with the prompt, "Investigate
these cells in data/tiny-dsa.xlsx. Which are meant to be constants,
and which user inputs? What are the expected input domains (e.g.,
permissible inputs that might be entered into user-configurable input
cells)?"
"""

# Required constraints
required_constraints = {
    "Inputs!A10": Literal["Borvelia"],
    "Inputs!A11": Literal["Litellia"],
    "Inputs!A12": Literal["Aurelium"],
    "Inputs!B22": Literal[1, 2, 3],
    "Inputs!B5": Literal["Borvelia", "Litellia", "Aurelium"],
}

# Additional constraints not required for dynamic ref resolution
# (included to support testing of the extraction pipeline)
_cols = ("C", "D", "E", "F", "G")
constraints = required_constraints | {
    "Engine!C5": Literal[1],
    "Engine!D5": Literal[2],
    "Engine!E5": Literal[3],
    "Engine!F5": Literal[4],
    "Engine!G5": Literal[5],
    "Inputs!B10": Annotated[float, RealBetween(0.0, 200.0)],
    "Inputs!B11": Annotated[float, RealBetween(0.0, 200.0)],
    "Inputs!B12": Annotated[float, RealBetween(0.0, 200.0)],
    "Inputs!B21": Annotated[int, Between(1, 5)],
    "Inputs!B26": Annotated[float, RealBetween(-30.0, 30.0)],
    "Inputs!C26": Annotated[float, RealBetween(-30.0, 30.0)],
    "Inputs!D26": Annotated[float, RealBetween(-30.0, 30.0)],
    **{f"Inputs!{c}16": Annotated[float, RealBetween(-10.0, 15.0)] for c in _cols},
    **{f"Inputs!{c}17": Annotated[float, RealBetween(0.0, 20.0)] for c in _cols},
    **{f"Inputs!{c}18": Annotated[float, RealBetween(-15.0, 15.0)] for c in _cols},
}

config = DynamicRefConfig.from_constraints(required_constraints, {})

LeafKind = Literal["input", "constant"]


def is_constant_constraint(constraint: object) -> bool:
    """True when the constraint fixes a single value (lookup/structural data)."""
    return get_origin(constraint) is Literal and len(get_args(constraint)) == 1


def classify_leaves_from_constraints(
    constraint_map: Mapping[str, object],
    leaf_keys: Iterable[str],
) -> dict[str, str]:
    """Classify graph leaves as inputs or constants from their constraints."""
    keys = list(leaf_keys)
    missing = [key for key in keys if key not in constraint_map]
    if missing:
        raise KeyError(f"missing constraints for leaf cells: {missing}")
    classification: dict[str, str] = {}
    for key in keys:
        kind: LeafKind = (
            "constant" if is_constant_constraint(constraint_map[key]) else "input"
        )
        classification[key] = kind
    return classification


# ------------------------------------------------------------
# Extract the graph
# ------------------------------------------------------------

graph: DependencyGraph = create_dependency_graph(
    workbook_path,
    targets,
    load_values=True,
    dynamic_refs=config,
)

binding_validation_report = validate_series_bindings(
    graph,
    series_bindings,
    workbook=workbook_path,
)
if not binding_validation_report["ok"]:
    raise ValueError(
        f"Invalid series bindings: {binding_validation_report['issues']!r}"
    )

input_series = derive_input_series(graph, series_bindings, workbook=workbook_path)
output_series = derive_output_series(graph, series_bindings, workbook=workbook_path)


# ------------------------------------------------------------
# Export the graph to Python code
# ------------------------------------------------------------


leaf_classification = classify_leaves_from_constraints(constraints, graph.leaf_keys())
graph.leaf_classification = leaf_classification

with CodeGenerator(graph) as generator:
    modules = generator.generate_modules(
        targets,
        series_bindings=series_bindings,
        bindings_workbook=workbook_path,
        series_docstring_callback=available_docstring_callback(),
        docstring_renderer="google",
    )

for filepath, code in modules.items():
    output_path = repo_root / "dist" / filepath
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(code, encoding="utf-8")
